/**
 * Created by Reinchard on 6/23/2017.
 */

// Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Users
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATA_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATA_USER_FAIL';
export const REMOVE_USER = 'REMOVE_USER';

//Modules
export const GET_MODULES_SUCCESS = 'GET_MODULES_SUCCESS';
export const GET_MODULES_FAIL = 'GET_MODULES_FAIL';
export const GET_MODULE_SUCCESS = 'GET_MODULE_SUCCESS';
export const GET_MODULE_FAIL = 'GET_MODULE_FAIL';

export const ON_REJECT_SUCCESS = 'ON_REJECT_SUCCESS';
export const ON_REJECT_FAIL = 'ON_REJECT_FAIL';
export const ON_APPROVE_SUCCESS = 'ON_REJECT_SUCCESS';
export const OON_APPROVE_FAIL = 'ON_REJECT_FAIL';


//Projects
export const GET_PROJECTS_SUCCESS = 'GET_MODULES_SUCCESS';
export const GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL';

export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const GET_PROJECT_FAIL = 'GET_PROJECT_SUCCESS';

export const REMOVE_PROJECT = 'REMOVE_PROJECT';

//Counts
export const COUNTS_SUCCESS = 'COUNTS_SUCCESS';
export const COUNTS_FAIL = 'COUNTS_FAIL';
